name: Delete Pinecone Data

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  delete-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install pinecone python-dotenv langchain
      
      - name: Run deletion script
        run: |
          git config user.email "jdominion123@gmail.com"
          git config user.name "DOMINION-JOHN1"
          clear_database.py
